version: '3'

volumes:
  vol-lock:

services:
  voltronic-mqtt:    
    image: bushrangers/ha-voltronic-mqtt    
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: voltronic-mqtt
    privileged: true
    environment:
        TZ: "Europe/Madrid"
    restart: always
    volumes:
        #- ./sources/inverter-py:/opt/inverter-py
        - ./config/:/etc/inverter/
    tmpfs:
      - /vol-lock 
    devices:
    #  - "/dev/mem:/dev/mem"
    # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm
    # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2