FROM debian:12.2

RUN apt update && apt install -y \
        curl \
        git \
        bash \
        build-essential \
        cmake \
        jq \
        mosquitto-clients \
        python3 \
        python3-pip \
        python3-venv \
        python3-paho-mqtt

ADD sources/ /opt/
ADD config/ /etc/inverter/

RUN cd /opt/inverter-cli && \
    mkdir bin && cmake . && make && mv inverter_poller bin/

WORKDIR /opt/inverter-py

# RUN python3 -m venv ./venv
# RUN . venv/bin/activate 
# RUN pip3 install -r requirements.txt

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt
ENTRYPOINT ["/bin/bash", "/opt/inverter-mqtt/entrypoint.sh"]
#ENTRYPOINT ["/bin/bash"]
